#!/usr/bin/env node
// Assembles src/person/*.ts, src/group/*.ts, src/event/*.ts in the caller's CWD
// into src/_generated/data-package.ts. Run from a data library's root.
//
// Usage:
//   assemble-data-package [--export-name=<name>]
//
// Conventions:
//   - Each per-record file default-exports a typed record
//   - Record `id` field must match the filename basename (sans `.ts`)

import { readdir, writeFile, mkdir } from "node:fs/promises";
import { join, basename } from "node:path";
import { pathToFileURL } from "node:url";
import type { Person, Group, Event, DataPackage } from "../src/types.js";

const cwd = process.cwd();

let exportName = "dataPackage";
let containsFirstNationsFlag = false;
let hasOptionalFirstNationsFlag = false;
for (const arg of process.argv.slice(2)) {
  if (arg.startsWith("--export-name=")) {
    exportName = arg.slice("--export-name=".length);
  } else if (arg === "--contains-first-nations") {
    containsFirstNationsFlag = true;
  } else if (arg === "--has-optional-first-nations") {
    hasOptionalFirstNationsFlag = true;
  }
}

async function loadKind<T extends { id: string }>(dir: string, kind: string): Promise<T[]> {
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return [];
  }
  const files = entries.filter((f) => f.endsWith(".ts")).sort();
  const items: T[] = [];
  for (const f of files) {
    const url = pathToFileURL(join(dir, f)).href;
    const mod = (await import(url)) as { default?: T };
    if (!mod.default) {
      throw new Error(`${kind}/${f}: missing default export`);
    }
    const item = mod.default;
    const expectedId = basename(f, ".ts");
    if (item.id !== expectedId) {
      throw new Error(`${kind}/${f}: id "${item.id}" does not match filename "${expectedId}"`);
    }
    items.push(item);
  }
  return items;
}

function assertUnique<T extends { id: string }>(items: T[], kind: string): void {
  const seen = new Set<string>();
  for (const item of items) {
    if (seen.has(item.id)) {
      throw new Error(`${kind}: duplicate id "${item.id}"`);
    }
    seen.add(item.id);
  }
}

function assertReferences(people: Person[], groups: Group[], events: Event[]): void {
  const groupIds = new Set(groups.map((g) => g.id));
  const personIds = new Set(people.map((p) => p.id));

  for (const p of people) {
    for (const gId of p.groupMemberships ?? []) {
      if (!groupIds.has(gId)) {
        throw new Error(`person ${p.id}: groupMemberships references missing group "${gId}"`);
      }
    }
  }
  for (const ev of events) {
    for (const aId of ev.attendeeIds) {
      if (!personIds.has(aId)) {
        throw new Error(`event ${ev.id}: attendeeIds references missing person "${aId}"`);
      }
    }
  }
}

function tsStringLiteral(s: string): string {
  return JSON.stringify(s);
}

function tsValue(value: unknown): string {
  if (value === null) return "null";
  if (value === undefined) return "undefined";
  if (value instanceof Date) return `new Date(${JSON.stringify(value.toISOString())})`;
  if (typeof value === "string") return tsStringLiteral(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return `[${value.map((v) => tsValue(v)).join(", ")}]`;
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).map(
      ([k, v]) => `${JSON.stringify(k)}: ${tsValue(v)}`,
    );
    return `{ ${entries.join(", ")} }`;
  }
  throw new Error(`Cannot serialize value of type ${typeof value}`);
}

function renderRecord(item: unknown): string {
  return tsValue(item);
}

async function main(): Promise<void> {
  const people = await loadKind<Person>(join(cwd, "src/person"), "person");
  const groups = await loadKind<Group>(join(cwd, "src/group"), "group");
  const events = await loadKind<Event>(join(cwd, "src/event"), "event");

  if (people.length === 0 && groups.length === 0 && events.length === 0) {
    throw new Error("No records found. Expected src/person/*.ts, src/group/*.ts, src/event/*.ts");
  }

  assertUnique(people, "person");
  assertUnique(groups, "group");
  assertUnique(events, "event");
  assertReferences(people, groups, events);

  const containsFirstNations = containsFirstNationsFlag || people.some((p) => p.isFirstNations === true);
  const hasOptionalFirstNations = hasOptionalFirstNationsFlag;

  const outDir = join(cwd, "src/_generated");
  await mkdir(outDir, { recursive: true });
  const outFile = join(outDir, "data-package.ts");

  const peopleLines = people.map((p) => `  ${renderRecord(p)},`).join("\n");
  const groupLines = groups.map((g) => `  ${renderRecord(g)},`).join("\n");
  const eventLines = events.map((e) => `  ${renderRecord(e)},`).join("\n");

  const ts = `// AUTO-GENERATED by assemble-data-package. Do not edit.
// Edit per-record source files under src/person/, src/group/, src/event/ instead.
import type { DataPackage } from '@mosaic-code/test-data-factory';

const people: DataPackage['people'] = [
${peopleLines}
];

const groups: DataPackage['groups'] = [
${groupLines}
];

const events: DataPackage['events'] = [
${eventLines}
];

export const ${exportName}: DataPackage = {
  people,
  groups,
  events,
  metadata: { containsFirstNationsPeople: ${containsFirstNations}${hasOptionalFirstNations ? ", hasOptionalFirstNations: true" : ""} },
};

export default ${exportName};
`;

  await writeFile(outFile, ts);
  console.log(
    `[assembled] ${people.length} people, ${groups.length} groups, ${events.length} events → src/_generated/data-package.ts`,
  );
}

main().catch((err) => {
  console.error("[assemble-data-package] " + (err as Error).message);
  process.exit(1);
});
